# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_players.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide2 import QtCore, QtGui, QtWidgets

# noinspection PyPep8Naming, PyArgumentList,PyAttributeOutsideInit, PyUnresolvedReferences
class Ui_Players(object):
    def setupUi(self, Players):
        Players.setObjectName("Players")
        Players.resize(400, 285)
        Players.setStyleSheet("background-color: rgb(211, 186, 0);")
        self.label = QtWidgets.QLabel(Players)
        self.label.setGeometry(QtCore.QRect(61, 16, 291, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Players)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(29, 70, 121, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_player1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_player1.setFont(font)
        self.label_player1.setObjectName("label_player1")
        self.verticalLayout.addWidget(self.label_player1)
        self.label_player2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_player2.setFont(font)
        self.label_player2.setObjectName("label_player2")
        self.verticalLayout.addWidget(self.label_player2)
        self.player1_name = QtWidgets.QLineEdit(Players)
        self.player1_name.setGeometry(QtCore.QRect(155, 82, 200, 28))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.player1_name.setFont(font)
        self.player1_name.setStyleSheet("background-color: rgb(75, 202, 213);\n"
"")
        self.player1_name.setObjectName("player1_name")
        self.player2_name = QtWidgets.QLineEdit(Players)
        self.player2_name.setGeometry(QtCore.QRect(155, 134, 200, 28))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.player2_name.setFont(font)
        self.player2_name.setStyleSheet("background-color: rgb(75, 202, 213);")
        self.player2_name.setObjectName("player2_name")
        self.compile_names_button = QtWidgets.QPushButton(Players)
        self.compile_names_button.setGeometry(QtCore.QRect(113, 199, 174, 58))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.compile_names_button.setFont(font)
        self.compile_names_button.setStyleSheet("background-color: rgb(23, 152, 128);\n"
"color: rgb(255, 239, 121);")
        self.compile_names_button.setObjectName("compile_names_button")

        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)

        self.retranslateUi(Players)
        QtCore.QMetaObject.connectSlotsByName(Players)

    # noinspection PyTypeChecker
    def retranslateUi(self, Players):
        _translate = QtCore.QCoreApplication.translate
        Players.setWindowTitle(_translate("Players", "Игроки"))
        self.label.setText(_translate("Players", "Введите имена игроков"))
        self.label_player1.setText(_translate("Players", "Игрок 1"))
        self.label_player2.setText(_translate("Players", "Игрок 2"))
        self.compile_names_button.setText(_translate("Players", "OK"))
