# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'end_winner_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_end_winner(object):
    def setupUi(self, end_winner):
        end_winner.setObjectName("end_winner")
        end_winner.setWindowModality(QtCore.Qt.WindowModal)
        end_winner.resize(400, 260)
        end_winner.setStyleSheet("background-color: rgb(255, 198, 128);")
        self.winning = QtWidgets.QLabel(end_winner)
        self.winning.setEnabled(True)
        self.winning.setGeometry(QtCore.QRect(70, 30, 260, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.winning.setFont(font)
        self.winning.setAlignment(QtCore.Qt.AlignCenter)
        self.winning.setObjectName("winning")
        self.end_of_win = QtWidgets.QLabel(end_winner)
        self.end_of_win.setGeometry(QtCore.QRect(45, 91, 310, 111))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.end_of_win.setFont(font)
        self.end_of_win.setText("")
        self.end_of_win.setAlignment(QtCore.Qt.AlignCenter)
        self.end_of_win.setObjectName("end_of_win")

        self.retranslateUi(end_winner)
        QtCore.QMetaObject.connectSlotsByName(end_winner)

    def retranslateUi(self, end_winner):
        _translate = QtCore.QCoreApplication.translate
        end_winner.setWindowTitle(_translate("end_winner", "Победитель"))
        self.winning.setText(_translate("end_winner", "Победил(а)"))
